[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "filelock-lts-py37"
version = "2025.68146"
description = "LTS patch for filelock (CVE-2025-68146) on Python 3.7. Replaces original filelock."
readme = "README.md"
requires-python = "==3.7.*"
license = { text = "Unlicense" }

[project.urls]
Homepage = "https://github.com/1minds3t/filelock-lts"

[tool.setuptools.packages.find]
where = ["src"]
